[workspace]
authors = ["Zhuofeng Wang <zhuofengwang2003@gmail.com>"]
channels = ["conda-forge"]
name = "staged-recipes"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rattler-build = ">=0.41.0,<0.42"
