context:
  name: openeb
  version: 5.1.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/prophesee-ai/openeb/releases/download/${{ version }}/Full.Source.Code.v${{ version }}.tar.gz
  sha256: 50561f027769331041c1d7b3a1ec720f7574ff203c32d5d94ecd512de99035fd
  patches:
    - 0001-conda-root-installation-path.patch

build:
  number: 4
  skip:
    - not (linux and x86_64)
  script:
    file: build.sh
    env:
      GITHUB_ACTIONS: ${{ env.get('GITHUB_ACTIONS', default='false') }}
  dynamic_linking:
    overdepending_behavior: ignore
    overlinking_behavior: ignore

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - pkgconfig
    - ninja
  host:
    - python
    - libgl-devel
    - libcanberra
    - zlib
    - libusb
    - libboost-devel
    - libopencv
    - pybind11
    - glew
    - glfw
    - hdf5
    - libprotobuf
    - pytest
    - patchelf
    - elfutils
  run:
    - h5py
    - numpy

tests:
  - python:
      imports:
        - metavision_sdk_base
        - metavision_core

about:
  homepage: https://github.com/prophesee-ai/openeb
  summary: |
    Open source SDK to create applications leveraging event-based vision hardware equipment
  description: |
    OpenEB is the open source project associated with Metavision SDK
    It enables anyone to get a better understanding of event-based
    vision, directly interact with events and build their own applications
    or camera plugins. As a camera manufacturer, ensure your customers benefit
    from the most advanced event-based software suite available by building your
    own plugin. As a creator, scientist, academic, join and contribute to the
    fast-growing event-based vision community.
  license: Apache-2.0
  license_file: licensing/LICENSE_OPEN
  documentation: https://docs.prophesee.ai/stable/index.html
  repository: https://github.com/prophesee-ai/openeb

extra:
  recipe-maintainers:
    - wzf03
