name: Build all packages

# this is important for trusted publishing
permissions:
  id-token: write

env:
  PREFIX_CHANNEL: wzf03

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-latest }
      fail-fast: false

    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.46.0
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Run code in changed subdirectories
        shell: bash
        run: |
          pixi run rattler-build build --recipe-dir . \
            --skip-existing=all --target-platform=${{ matrix.target }} \
            -c conda-forge -c https://prefix.dev/${PREFIX_CHANNEL}

      - name: Upload all packages
        shell: bash
        # do not upload on PR
        if: github.event_name == 'push'
        run: |
          for file in output/**/*.conda; do
            rattler-build upload prefix -c ${PREFIX_CHANNEL} "$file"
          done